version: "3"
services:
  springboot-app:
    container_name: spring-hello-world
    image: github-gke-deployment-ghcr
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8082:8082