FROM ubuntu:rolling
RUN apt-get update && apt-get install -y openjdk-17-jdk
WORKDIR /app
COPY target/hello-gcp-0.0.1-SNAPSHOT.jar /app/hello-gcp-0.0.1-SNAPSHOT.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/app/hello-gcp-0.0.1-SNAPSHOT.jar"]