FROM ubuntu:rolling

RUN apt-get update && apt-get install -y openjdk-17-jdk

COPY target/hello-gcp-0.0.1-SNAPSHOT.jar hello-gcp-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/hello-gcp-0.0.1-SNAPSHOT.jar"]