FROM adoptopenjdk:17-jdk-hotspot
WORKDIR /app
COPY target/hello-gcp-0.0.1-SNAPSHOT.jar /app/hello-gcp-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/hello-gcp/target/hello-gcp-0.0.1-SNAPSHOT.jar"]