name: Docker Image Publish
on:
  push:
    branches: [master]
    tags: ['v*.*.*']
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.11.0'
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          
          docker login --username $username --password $password ghcr.io
          docker build . --tag ghcr.io/riyaknol11/github-gke-deployment:latest
          docker push ghcr.io/riyaknol11/github-gke-deployment:latest