name: Docker Image Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          
          docker login --username $username --password $password ghcr.io
          docker build . --tag ghcr.io/riyaknol11/github-gke-deployment:latest
          docker push ghcr.io/riyaknol11/github-gke-deployment:latest
      - name: Deploy to GKE
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/




